// <auto-generated />
namespace System_Project_Group14.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GradYear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GradYear));
        
        string IMigrationMetadata.Id
        {
            get { return "201604270302112_GradYear"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
